insert.class: insert.java miditxt.java miditxt.class
	javac -classpath ${CLASSPATH}:. insert.java

miditxt.class: miditxt.java
	javac miditxt.java

clean:
	rm insert.class miditxt.class MyFilter.class
